#!/usr/bin/env python3

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Copyright(C) 2025 Max-Planck-Society
#
# NIFTy is being developed at the Max-Planck-Institut fuer Astrophysik.

"""Demo: spatio-spectral false-colour visualization.

Draws a 2-D × 1-D (256×256 spatial pixels × 16 spectral bins) log-normal
correlated field from a prior with steep loglogavgslope = -4 and the same
nonparametric fluctuation model in every dimension.  Using a single 3-D
add_fluctuations call produces a non-separable field where the spectral shape
genuinely varies from pixel to pixel (a separable model would give identical
spectra at every location and hence a greyscale image).

The field is projected to sRGB via SpectrumToRGBProjector (energy mode).
Four equally-spaced spectral slices are shown alongside, and a colour map
legend generated by get_color_map_image shows which visible colour corresponds
to each spectral bin and at what relative brightness.
"""

import jax
import jax.numpy as jnp
import matplotlib.pyplot as plt
import numpy as np
import nifty.re as jft
from matplotlib.colors import LogNorm

from nifty.cl.spectrum_to_rgb import SpectrumToRGBProjector

jax.config.update("jax_enable_x64", True)

# ---------------------------------------------------------------------------
# Field dimensions
# ---------------------------------------------------------------------------
nx, ny = 256, 256           # spatial pixels
n_spec = 16                 # spectral bins (after de-padding)
n_spec_padded = n_spec + n_spec // 2   # +50 % to avoid periodic BC wrap-around

seed = 43
key = jax.random.PRNGKey(seed)

use_log_compression = True

# ---------------------------------------------------------------------------
# Correlated field — steep power spectrum, same model in every dimension
#
# A single 3-D add_fluctuations call is essential: two separate calls
# (one spatial, one spectral) would produce a separable log-field
#   log_signal(x, y, k) = spatial(x, y) + spectral(k)
# so every pixel has the same spectral shape (just a different amplitude)
# and the false-colour image collapses to greyscale.  With a single 3-D call
# the three dimensions are correlated jointly, giving each pixel its own
# spectral shape.
# ---------------------------------------------------------------------------
cfm = jft.CorrelatedFieldMaker("cf")
cfm.set_amplitude_total_offset(offset_mean=0., offset_std=(1e-3, 1e-32))
cfm.add_fluctuations(
    (nx, ny, n_spec_padded),
    distances=(1. / nx, 1. / ny, 1. / n_spec_padded),
    fluctuations=(0.85, 1e-32),
    loglogavgslope=(-3., 1e-32),
    prefix="cf",
    non_parametric_kind="power",
)
cf = cfm.finalize()

key, subkey = jax.random.split(key)
latent = jft.random_like(subkey, cf.domain)
log_signal = cf(latent)                           # shape: (nx, ny, n_spec_padded)
signal = np.array(jnp.exp(log_signal))[:, :, :n_spec]   # de-pad; (nx, ny, n_spec)

# ---------------------------------------------------------------------------
# SpectrumToRGBProjector
#
# spectral_axis_type='energy': bin 0 (lowest energy) → red end,
#                              bin n_spec-1 (highest energy) → blue end.
# visible_bin_width='uniform': every bin receives the same visible Δλ,
#                              appropriate for equi-spaced abstract-index bins.
# ---------------------------------------------------------------------------
bin_width = 1.0
centers = bin_width * (0.5 + np.arange(n_spec))
widths = np.full(n_spec, bin_width)

proj = SpectrumToRGBProjector(
    spectral_axis_type='energy',
    visible_bin_width='uniform',
    flux_convention='bin_integrated_flux',
)
proj.specify_input_spectrum_bins_via_center_and_width(centers, widths)

# ---------------------------------------------------------------------------
# Fix the displayed luminance range
#
# The range is asked of the data itself: the 30th percentile of the pixel
# luminances becomes black, the 99.9th becomes white.  Fixing it as object
# state (rather than letting each image normalise to its own maximum) is what
# makes separate renderings comparable — and what makes the colour-map legend
# below agree with the image.
# ---------------------------------------------------------------------------
black, white = proj.luminance_quantiles(signal.reshape(-1, n_spec),
                                        q=(0.3, 0.999))
proj.set_luminance_range(white=white, black=black)
if use_log_compression:
    proj.use_log_compression()

# ---------------------------------------------------------------------------
# Project spatio-spectral field to sRGB
# ---------------------------------------------------------------------------
rgb_image = proj.project(signal.reshape(-1, n_spec)).reshape(nx, ny, 3)

# ---------------------------------------------------------------------------
# Colour map legend
#
# get_color_map_image returns (n_levels, n_spec, 3): each row is a flux level
# (dim → bright) and each column is a spectral bin.  Row i, column k shows how
# a spectrum carrying flux levels[i] in bin k alone is rendered — no per-column
# rescaling, so the fact that mid-spectrum bins are intrinsically brighter than
# the red and blue ends stays visible.  The tone curve comes from the
# projection above.
#
# The levels deliberately reach far beyond the per-bin fluxes present in the
# data: a pixel emitting in one bin only needs roughly 40 (green end) to 460
# (blue end) flux units to reach the same luminance a 16-bin spectrum reaches
# with ~2 per bin.  Picking levels is a domain decision, which is why the
# projector asks for them rather than inventing a reference spectrum.
# ---------------------------------------------------------------------------
levels = np.geomspace(1e0, 1e3, 64) if use_log_compression \
    else np.linspace(0., 500., 64)
colormap_image = proj.get_color_map_image(levels=levels)
# shape: (n_levels, n_spec, 3)

# ---------------------------------------------------------------------------
# Spectral slices: 4 equally-spaced bins shown as spatial images
# ---------------------------------------------------------------------------
# Bins at the red, green, and blue ends of the visible range.
# With energy mode and the default 440–640 nm mapping, each bin spans
# 200/n_spec nm and centres land at approximately:
#   bin 0       → ~634 nm  (red)
#   bin n//2    → ~534 nm  (green, near the CIE luminous-efficiency peak)
#   bin n_spec-1 → ~446 nm (blue)
slice_bins = [0, n_spec // 2, n_spec - 1]
slice_labels = ["red end (~634 nm)", "green (~534 nm)", "blue end (~446 nm)"]
log_vmin = signal.min()
log_vmax = signal.max()

# ---------------------------------------------------------------------------
# Figure layout
#   row 0 (large)  : false-colour image
#   row 1 (medium) : 3 spectral slices at primary colours
#   row 2 (thin)   : colour map legend
# ---------------------------------------------------------------------------
fig = plt.figure(figsize=(10, 12))
gs = fig.add_gridspec(
    3, 3,
    height_ratios=[5, 2.5, 0.6],
    hspace=0.35,
    wspace=0.08,
)

# -- Main false-colour image -------------------------------------------------
ax_img = fig.add_subplot(gs[0, :])
ax_img.imshow(
    rgb_image.transpose(1, 0, 2),   # (ny, nx, 3) with y upward
    origin='lower',
    extent=[0, 1, 0, 1],
)
ax_img.set_title(r"Spatio-spectral log-normal field", fontsize=12)
ax_img.set_xlabel("x")
ax_img.set_ylabel("y")

# -- Spectral slices ---------------------------------------------------------
norm = LogNorm(vmin=log_vmin, vmax=log_vmax)
ax_slices = []
for col, (k, label) in enumerate(zip(slice_bins, slice_labels)):
    ax = fig.add_subplot(gs[1, col])
    im = ax.imshow(
        signal[:, :, k].T,
        origin='lower',
        extent=[0, 1, 0, 1],
        cmap='inferno',
        norm=norm,
    )
    ax.set_title(f"Bin {k + 1} — {label}", fontsize=9)
    ax.set_xlabel("x", fontsize=8)
    if col == 0:
        ax.set_ylabel("y", fontsize=8)
    else:
        ax.set_yticklabels([])
    ax.tick_params(labelsize=7)
    ax_slices.append(ax)

fig.colorbar(im, ax=ax_slices, orientation='vertical',
             fraction=0.02, pad=0.01, label="signal (log scale)")

# -- Colour map legend -------------------------------------------------------
ax_cb = fig.add_subplot(gs[2, :])
ax_cb.imshow(
    colormap_image,
    origin='lower',
    aspect='auto',
    extent=[0.5, n_spec + 0.5, 0, 1],
)
ax_cb.set_title(
    "Colour map legend: spectral bin  ×  relative flux  "
    r"(bin 1 = red end, bin {:d} = blue end)".format(n_spec),
    fontsize=9, pad=3,
)
ax_cb.set_xlabel("spectral bin index", fontsize=9)
ax_cb.set_ylabel("rel.\nflux", fontsize=7, rotation=0, labelpad=28)
ax_cb.set_xticks(np.arange(1, n_spec + 1))
ax_cb.tick_params(axis='x', labelsize=7)
# Round-numbered flux ticks, positioned from the extent the image was drawn with
proj.apply_color_map_ticks(ax_cb, axis='y', n_ticks=4)
ax_cb.tick_params(axis='y', labelsize=7)

fig.savefig("a_spatio-spectral_plotting.png", dpi=150, bbox_inches='tight')
plt.show()
